# -*- coding: utf-8 -*-
"""FinalLipSync.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dC9RCgcavzBEP-kZqJ9wbtKu9EiHsn_m
"""

!nvidia-smi

from google.colab import drive
drive.mount('/content/gdrive')

!git clone https://github.com/Rudrabha/Wav2Lip.git

!cp -ri "/content/gdrive/MyDrive/Wav2Lip/wav2lip.pth" /content/Wav2Lip/checkpoints/

!cp -ri "/content/gdrive/MyDrive/Wav2Lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/

!cd Wav2Lip && pip install -r requirements.txt

!wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "Wav2Lip/face_detection/detection/sfd/s3fd.pth"

!pip install librosa==0.9.1


!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "/content/gdrive/MyDrive/Wav2Lip/video1.mp4" --audio "/content/gdrive/MyDrive/Wav2Lip/audio.wav"

